#type: args

global:
  random_seed: 0
  need_preprocess: False # 1.是否要进行数据处理

dataset:
  dataset_name: "Thunderbird"
  dir: "dataset"
  emb_dim: 768 # word2vec vector size
  window_size: 20 # size of sliding window
  step_size: 4 # step size of sliding window
  total_num: 20000 # Maximum number of source datasets
  start_index: 2650000
  need_Bart: False
  train_ratio: 0.7
  test_ratio: 0.5

train:
   epoch: 100
   batch_size: 512

contrastive:
   margin: 1
   epoch: 100
   ratio: 0.2
   alpha: 5

anomaly_detection: # 异常检测相关参数
  ratio: 0.1
  n_std: 2

# 0.2 ? 0.1
Emb2Rep:
  isUsed: True
  rnn_hidden_dim: 512 # lstm输出
  num_heads: 8 #
  rep_dim: 128 # 最后输出的维度

AE:
  hidden_dims: [64,128,14]
  model_path: "./save/model/bgl_detection.pkl"
  lr : 0.001
